server:
  port: 8080
  servlet:
    context-path: /desafio-framework

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    initialization-mode: always
    schema:
    - classpath:/data.sql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    generate-ddl: false
      